language: ruby
cache: bundler
sudo: false

rvm:
  - 2.5.3

jdk: 'oraclejdk8'

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script:
  - bundle exec rake uri_service:setup:config_files
